### ISSUE TITLE
Lot Description

### ISSUE THREAD

**Issue by ISOOO7** [LogicBolt/Ton-betting-contract-with-Func#1]
you know, you did announce the description is limited on one cell, so have to do sneak,
but even now I can't see any update about that...
Perhaps you already implemented on private repo but not update on public yet?
pls update it as soon as possible.

**Comment by LogicBolt** [comment]
> you know, you did announce the description is limited on one cell, so have to do sneak, but even now I can't see any update about that... Perhaps you already implemented on private repo but not update on public yet? pls update it as soon as possible.

OK, will update soon, you can check next Monday

**Comment by ISOOO7** [comment]
ok thx
